# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title                    : Ducky Dares Archives
email                    : duckydares@protonmail.com
description              : >- # this means to ignore newlines until "baseurl:"
  An archival of all the things I, Ducky, have experienced, engaged in, and learned. Consider this site
  a repository of coding projects, learning templates for various fields, and a personal blog.
url                      : https://duckydares.duckiverse # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
twitter_username         : PimpingTakis
github_username          : duckydares
minimal_mistakes_skin    : dark
search                   : true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 0 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - .htaccess
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Ducky"
  avatar : "/assets/images/toyko_revengers_mikey_1.png"
  bio    : "Holding it down for the team while trying not to lose myself."
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/duckydares"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/duckydares"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

# Collections
collections:
  experiences:
    output: true
    permalink: /:collection/:path/
  learning:
    output: true
    permalink: /:collection/:path/
  music:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: false
  # experiences
  - scope:
      path: ""
      type: experiences
    values:
      layout: default
      author_profile: false
  # learning
  - scope:
      path: ""
      type: learning
    values:
      layout: default
      author_profile: false
  # music
  - scope:
      path: ""
      type: music
    values:
      layout: default
      author_profile: false
  # projects
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      author_profile: false
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
